# Javascript Node CircleCI 2.0 configuration file
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:12.14.1
              environment: 
                TEST_DB_USER: my_user
                TEST_DB_NAME: my_test_db
           
            - image: postgres:9.6.2-alpine
              environment:
                POSTGRES_USER: my_user
                POSTGRES_DB: my_test_db

          

        working_directory: ~/volunteersng-api

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: npm install

            - run:
                name: Setup Code Climate test-reporter
                command: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
                  chmod +x ./cc-test-reporter

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            # run tests!
            - run:
                name: Run Test and Coverage
                command: |
                  ./cc-test-reporter before-build
                  npm test
                  ./cc-test-reporter after-build --coverage-input-type lcov ./coverage/lcov.info --exit-code $?
         
